# Generated by Django 5.2.6 on 2025-10-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Watching', 'Watching'), ('Completed', 'Completed'), ('Plan to Watch', 'Plan to Watch')], max_length=20)),
                ('release_year', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
